### ISSUE TITLE
How to export these files from seurat object？

### ISSUE THREAD

**Issue by geng-lee** [SCimpleton/Seurat-to-SCvelo#1]
Hi,

How to export these files from seurat object？

"cellID_obs_seurat.csv"
"cell_embeddings_seurat.csv"
"clusters_obs_seurat.csv"
"cluster_annot_seurat.csv"

Thanks!

best,
jamie

**Comment by SCimpleton** [comment]
Sorry Jamie
got sidetracked and never got round to finishing these - i have now updated it
hope it helps!

**Comment by geng-lee** [comment]
Let me try. Thank you so much!😁

best，
Jamie
